export const products = [
  {
    id: 1,
    title: "Empanada carne",
    price: 300,
    stock: 100,
    category: "Empanadas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574464/empanadas2_lrx7dd.webp",
  },
  {
    id: 2,
    title: "Empanada pollo",
    price: 300,
    stock: 100,
    category: "Empanadas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574544/empanadas3_jxiocf.webp",
  },
  {
    id: 3,
    title: "Guiso de lentejas",
    price: 2200,
    stock: 30,
    category: "Comidas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574579/lentejas_rabqv2.webp",
  },
  {
    id: 4,
    title: "Humita en chala",
    price: 1300,
    stock: 40,
    category: "Comidas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574563/humita_qdi4ck.webp",
  },
  {
    id: 5,
    title: "Locro",
    price: 2200,
    stock: 30,
    category: "Comidas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574593/locro_qzhqzc.webp",
  },
  {
    id: 6,
    title: "Pizza mozzarella",
    price: 1600,
    stock: 100,
    category: "Pizzas",
    img: "https://res.cloudinary.com/ddwaowcsz/image/upload/v1678574608/pizza_gxockk.webp",
  },
];
